version: '3.8'

services:
  redis:
    image: "redis"
    ports:
      - "6379:6379"

  myapp:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock